config/routes.rb
Rails.application.routes.draw do 

  root 'quiz_modules#index'
 	resources :quiz_modules, only: :index  do 
		get '/start' => 'pages#start'
		resources :pages, only: [:index, :show]
	end
  resources :scorings

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_many :scorings

  belongs_to :question

  scope :answer, -> { where(type: nil).first }
  scope :wrong_answers, ->{ where type: 'WrongAnswer' }


  def answer_label
    letter.present? ? "#{letter}. #{text}" : "#{text}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :question
	belongs_to :quiz_module
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :quiz_module
	has_one :page
  has_many :answers

  delegate :answer, :wrong_answers, to: :answers
end

app/models/quiz_module.rb
class QuizModule < ActiveRecord::Base
  has_many :questions
	has_many :pages
  has_many :scores
end

app/models/score.rb
class Score < ActiveRecord::Base
	has_many :scorings
  belongs_to :quiz_module

  accepts_nested_attributes_for :scorings
end

app/models/scoring.rb
class Scoring < ActiveRecord::Base
	belongs_to :score
	belongs_to :answer
end

app/models/wrong_answer.rb
class WrongAnswer < Answer  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
	  @pages = Page.all
	end
  
  def show
	  @page = Page.find params[:id]
	  @scoring = Scoring.new
	end

	def start
		@quiz = QuizModule.find(params[:quiz_module_id])
		@pages = @quiz.pages.sort_by{|x| x.number.to_i}
		@page = @pages.first
		cookies[:current_score_id] = Score.create(quiz_module: @quiz).id
		redirect_to quiz_module_page_path(@quiz, @page)
	end

end

app/controllers/quiz_modules_controller.rb
class QuizModulesController < ApplicationController
	def index
		@modules = QuizModule.all
	end




end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  
#   def start_quiz
#     quiz = QuizModule.find(params[:quiz_module_id])
#     @score = Score.create(quiz_module: quiz)

#     cookies[:current_score_id] = @score.id

#     redirect_to quiz_module_page_path quiz
#   end

  def grade
    
  end

# private
#   def score_params
#     params.require(:score).permit(:quiz_module)
#   end
end

app/controllers/scorings_controller.rb
class ScoringsController < ApplicationController

  def create
    params[:scoring][:score_id] = cookies[:current_score_id]
    @scoring = Scoring.create scoring_params
    if @scoring.save
      quiz_module = params[:scoring][:quiz_module]
      number = params[:scoring][:current_page].to_i
      next_page = Page.where( number: (number+1), quiz_module_id: quiz_module).first
      redirect_to quiz_module_page_path(quiz_module, next_page) 
    end
  end

  private
    def scoring_params
      params.require(:scoring).permit(:answer_id, :score_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def next_page(page)
		 next_num = page.number.to_i + 1
		 qm = page.quiz_module	
		if next_num <= qm.pages.count
			next_page = qm.pages.where(number: next_num).first
		  link_to 'Next Page', quiz_module_page_path(qm, next_page) 
		else
			# last page
			
			link_to "Submit Score"
		end

  end


end

app/helpers/quiz_modules_helper.rb
module QuizModulesHelper
end

app/views/layouts/application.html.slim
doctype html
html
head
  title QuizApp
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinkstrack' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 

body
  header
    - if @page
      | Module: #{ @page.quiz_module.title } 
  .container
    = yield 

app/views/pages/show.html.slim
h4  
	= @page.header

= @page.text unless @page.blank?

-if @page.question
  p= @page.question.text

  = simple_form_for @scoring do |f|
    = f.association :answer, label_method: :answer_label, collection: @page.question.answers, as: :radio_buttons 
    = f.input :current_page, as: :hidden, input_html: {value: @page.number}
    = f.input :quiz_module, as: :hidden, input_html: {value: @page.quiz_module.id}
    = f.button :submit, value: "Submit"

- unless @page.question
  p= next_page @page

app/views/quiz_modules/index.html.slim
h2 Quiz Modules

- @modules.each do |mod|
  p 
   |Module #{mod.id} #{mod.title}  
   = link_to "Start", quiz_module_start_path(mod) 
     